# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a51c6348b63f08247592f02c74ae1aa1"
name = "greenstand-wallet-app"
application_url = "https://males-expansys-resource-springfield.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "greenstand-wallet-extension.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://males-expansys-resource-springfield.trycloudflare.com/auth/callback",
  "https://males-expansys-resource-springfield.trycloudflare.com/auth/shopify/callback",
  "https://males-expansys-resource-springfield.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
